# Generated by Django 5.0.3 on 2024-07-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference_field',
            new_name='ref',
        ),
    ]
